openapi: 3.0.0
info:
  description: >-
    The Azure SQL Database management API provides a RESTful set of web APIs
    that interact with Azure SQL Database services to manage your databases. The
    API enables users to create, retrieve, update, and delete databases,
    servers, and other entities.
  title: SqlManagementClient
  version: 2017-03-01-preview
servers:
  - url: 'https://management.azure.com/'
paths:
  '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/vulnerabilityAssessments':
    get:
      parameters:
        - $ref: '#/components/parameters/ResourceGroupParameter'
        - $ref: '#/components/parameters/ServerNameParameter'
        - description: >-
            The name of the database for which the vulnerability assessment
            policies are defined.
          in: path
          name: databaseName
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/ApiVersionParameter'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatabaseVulnerabilityAssessmentListResult'
          description: >-
            Successfully retrieved the database vulnerability assessment
            policies.
        default:
          description: |-
            *** Error Responses: ***

             * 400 InvalidStorageAccountName - The provided storage account is not valid or does not exist.

             * 400 InvalidStorageAccountCredentials - The provided storage account shared access signature or account storage key is not valid.

             * 400 VulnerabilityAssessmentInvalidPolicy - Vulnerability Assessment settings don't exist or invalid storage specified in settings. 

             * 400 DatabaseVulnerabilityAssessmentMissingStorageContainerPath - Storage container path must be provided if it isn't set in server level policy

             * 400 VulnerabilityAssessmentDatawarehouseDatabaseIsDeactivated - Could not execute Vulnerability Assessment operation because the database is paused. Please resume it.

             * 404 SubscriptionDoesNotHaveServer - The requested server was not found

             * 404 SourceDatabaseNotFound - The source database does not exist.

             * 404 DatabaseDoesNotExist - User has specified a database name that does not exist on this server instance.

             * 409 DatabaseVulnerabilityAssessmentScanIsAlreadyInProgress - Vulnerability Assessment scan is already in progress.

             * 500 DatabaseIsUnavailable - Loading failed. Please try again later.
      tags:
        - DatabaseVulnerabilityAssessments
      description: Lists the vulnerability assessment policies associated with a database.
      operationId: DatabaseVulnerabilityAssessments_ListByDatabase
      x-ms-examples:
        Get the database's vulnerability assessment policies:
          $ref: ./examples/DatabaseVulnerabilityAssessmentListByDatabase.json
      x-ms-pageable:
        nextLinkName: nextLink
  '/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Sql/servers/{serverName}/databases/{databaseName}/vulnerabilityAssessments/{vulnerabilityAssessmentName}':
    delete:
      parameters:
        - $ref: '#/components/parameters/ResourceGroupParameter'
        - $ref: '#/components/parameters/ServerNameParameter'
        - description: >-
            The name of the database for which the vulnerability assessment is
            defined.
          in: path
          name: databaseName
          required: true
          schema:
            type: string
        - description: The name of the vulnerability assessment.
          in: path
          name: vulnerabilityAssessmentName
          required: true
          schema:
            enum:
              - default
            type: string
          x-ms-enum:
            modelAsString: true
            name: VulnerabilityAssessmentName
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/ApiVersionParameter'
      responses:
        '200':
          description: Successfully removed the database vulnerability assessment.
        default:
          description: |-
            *** Error Responses: ***

             * 400 InvalidStorageAccountName - The provided storage account is not valid or does not exist.

             * 400 InvalidStorageAccountCredentials - The provided storage account shared access signature or account storage key is not valid.

             * 400 DatabaseVulnerabilityAssessmentMissingStorageContainerPath - Storage container path must be provided if it isn't set in server level policy

             * 404 SubscriptionDoesNotHaveServer - The requested server was not found

             * 404 SourceDatabaseNotFound - The source database does not exist.

             * 404 DatabaseDoesNotExist - User has specified a database name that does not exist on this server instance.

             * 500 DatabaseIsUnavailable - Loading failed. Please try again later.
      tags:
        - DatabaseVulnerabilityAssessments
      description: Removes the database's vulnerability assessment.
      operationId: DatabaseVulnerabilityAssessments_Delete
      x-ms-examples:
        Remove a database's vulnerability assessment:
          $ref: ./examples/DatabaseVulnerabilityAssessmentDelete.json
    get:
      parameters:
        - $ref: '#/components/parameters/ResourceGroupParameter'
        - $ref: '#/components/parameters/ServerNameParameter'
        - description: >-
            The name of the database for which the vulnerability assessment is
            defined.
          in: path
          name: databaseName
          required: true
          schema:
            type: string
        - description: The name of the vulnerability assessment.
          in: path
          name: vulnerabilityAssessmentName
          required: true
          schema:
            enum:
              - default
            type: string
          x-ms-enum:
            modelAsString: true
            name: VulnerabilityAssessmentName
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/ApiVersionParameter'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatabaseVulnerabilityAssessment'
          description: Successfully retrieved the database vulnerability assessment.
        default:
          description: |-
            *** Error Responses: ***

             * 400 InvalidStorageAccountName - The provided storage account is not valid or does not exist.

             * 400 InvalidStorageAccountCredentials - The provided storage account shared access signature or account storage key is not valid.

             * 400 DatabaseVulnerabilityAssessmentMissingStorageContainerPath - Storage container path must be provided if it isn't set in server level policy

             * 404 SubscriptionDoesNotHaveServer - The requested server was not found

             * 404 SourceDatabaseNotFound - The source database does not exist.

             * 404 DatabaseDoesNotExist - User has specified a database name that does not exist on this server instance.

             * 500 DatabaseIsUnavailable - Loading failed. Please try again later.
      tags:
        - DatabaseVulnerabilityAssessments
      description: Gets the database's vulnerability assessment.
      operationId: DatabaseVulnerabilityAssessments_Get
      x-ms-examples:
        Get a database's vulnerability assessment:
          $ref: ./examples/DatabaseVulnerabilityAssessmentGet.json
    put:
      parameters:
        - $ref: '#/components/parameters/ResourceGroupParameter'
        - $ref: '#/components/parameters/ServerNameParameter'
        - description: >-
            The name of the database for which the vulnerability assessment is
            defined.
          in: path
          name: databaseName
          required: true
          schema:
            type: string
        - description: The name of the vulnerability assessment.
          in: path
          name: vulnerabilityAssessmentName
          required: true
          schema:
            enum:
              - default
            type: string
          x-ms-enum:
            modelAsString: true
            name: VulnerabilityAssessmentName
        - $ref: '#/components/parameters/SubscriptionIdParameter'
        - $ref: '#/components/parameters/ApiVersionParameter'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatabaseVulnerabilityAssessment'
          description: Successfully set the vulnerability assessment.
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatabaseVulnerabilityAssessment'
          description: Successfully created the vulnerability assessment.
        default:
          description: |-
            *** Error Responses: ***

             * 400 InvalidStorageAccountName - The provided storage account is not valid or does not exist.

             * 400 InvalidStorageAccountCredentials - The provided storage account shared access signature or account storage key is not valid.

             * 400 DatabaseVulnerabilityAssessmentMissingStorageContainerPath - Storage container path must be provided if it isn't set in server level policy

             * 400 InvalidVulnerabilityAssessmentOperationRequest - The vulnerability assessment operation request does not exist or has no properties object.

             * 400 DataSecurityInvalidUserSuppliedParameter - An invalid parameter value was provided by the client.

             * 404 SubscriptionDoesNotHaveServer - The requested server was not found

             * 404 SourceDatabaseNotFound - The source database does not exist.

             * 404 DatabaseDoesNotExist - User has specified a database name that does not exist on this server instance.

             * 500 DatabaseIsUnavailable - Loading failed. Please try again later.
      tags:
        - DatabaseVulnerabilityAssessments
      description: Creates or updates the database's vulnerability assessment.
      operationId: DatabaseVulnerabilityAssessments_CreateOrUpdate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatabaseVulnerabilityAssessment'
        description: The requested resource.
        required: true
      x-ms-examples:
        Create a database's vulnerability assessment with all parameters:
          $ref: ./examples/DatabaseVulnerabilityAssessmentCreateMax.json
        'Create a database''s vulnerability assessment with minimal parameters, when storageAccountAccessKey is specified':
          $ref: >-
            ./examples/DatabaseVulnerabilityAssessmentCreateStorageAccessKeyMin.json
        'Create a database''s vulnerability assessment with minimal parameters, when storageContainerSasKey is specified':
          $ref: >-
            ./examples/DatabaseVulnerabilityAssessmentCreateContainerSasKeyMin.json
components:
  parameters:
    ApiVersionParameter:
      description: The API version to use for the request.
      in: query
      name: api-version
      required: true
      schema:
        type: string
      x-ms-parameter-location: client
    BlobAuditingPolicyNameParameter:
      description: The name of the blob auditing policy.
      in: path
      name: blobAuditingPolicyName
      required: true
      schema:
        enum:
          - default
        type: string
      x-ms-parameter-location: method
    DatabaseNameParameter:
      description: The name of the database.
      in: path
      name: databaseName
      required: true
      schema:
        type: string
      x-ms-parameter-location: method
    ManagedInstanceNameParameter:
      description: The name of the managed instance.
      in: path
      name: managedInstanceName
      required: true
      schema:
        type: string
      x-ms-parameter-location: method
    ResourceGroupParameter:
      description: >-
        The name of the resource group that contains the resource. You can
        obtain this value from the Azure Resource Manager API or the portal.
      in: path
      name: resourceGroupName
      required: true
      schema:
        type: string
      x-ms-parameter-location: method
    ServerNameParameter:
      description: The name of the server.
      in: path
      name: serverName
      required: true
      schema:
        type: string
      x-ms-parameter-location: method
    SqlVirtualMachineContainerNameParameter:
      description: The name of the SqlVirtualMachineContainer.
      in: path
      name: sqlVirtualMachineContainerName
      required: true
      schema:
        type: string
      x-ms-parameter-location: method
    SqlVirtualMachineInstanceNameParameter:
      description: The name of the SqlVirtualMachineInstance.
      in: path
      name: sqlVirtualMachineInstanceName
      required: true
      schema:
        type: string
      x-ms-parameter-location: method
    SubscriptionIdParameter:
      description: The subscription ID that identifies an Azure subscription.
      in: path
      name: subscriptionId
      required: true
      schema:
        type: string
      x-ms-parameter-location: client
    VirtualClusterNameParameter:
      description: The name of the virtual cluster.
      in: path
      name: virtualClusterName
      required: true
      schema:
        type: string
      x-ms-parameter-location: method
  schemas:
    DatabaseVulnerabilityAssessment:
      allOf:
        - $ref: ../../../common/v1/types.json#/definitions/ProxyResource
      description: A database vulnerability assessment.
      properties:
        properties:
          $ref: '#/components/schemas/DatabaseVulnerabilityAssessmentProperties'
          description: Resource properties.
          x-ms-client-flatten: true
      type: object
    DatabaseVulnerabilityAssessmentListResult:
      description: A list of the database's vulnerability assessments.
      properties:
        nextLink:
          description: Link to retrieve next page of results.
          readOnly: true
          type: string
        value:
          description: Array of results.
          items:
            $ref: '#/components/schemas/DatabaseVulnerabilityAssessment'
          readOnly: true
          type: array
      type: object
    DatabaseVulnerabilityAssessmentProperties:
      description: Properties of a database Vulnerability Assessment.
      properties:
        recurringScans:
          $ref: '#/components/schemas/VulnerabilityAssessmentRecurringScansProperties'
          description: The recurring scans settings
        storageAccountAccessKey:
          description: >-
            Specifies the identifier key of the storage account for
            vulnerability assessment scan results. If 'StorageContainerSasKey'
            isn't specified, storageAccountAccessKey is required.
          type: string
          x-ms-mutability:
            - create
            - update
        storageContainerPath:
          description: >-
            A blob storage container path to hold the scan results (e.g.
            https://myStorage.blob.core.windows.net/VaScans/).  It is required
            if server level vulnerability assessment policy doesn't set
          type: string
          x-ms-mutability:
            - create
            - update
        storageContainerSasKey:
          description: >-
            A shared access signature (SAS Key) that has read and write access
            to the blob container specified in 'storageContainerPath' parameter.
            If 'storageAccountAccessKey' isn't specified, StorageContainerSasKey
            is required.
          type: string
          x-ms-mutability:
            - create
            - update
      type: object
    VulnerabilityAssessmentRecurringScansProperties:
      description: Properties of a Vulnerability Assessment recurring scans.
      properties:
        emailSubscriptionAdmins:
          default: true
          description: >-
            Specifies that the schedule scan notification will be is sent to the
            subscription administrators.
          type: boolean
        emails:
          description: >-
            Specifies an array of e-mail addresses to which the scan
            notification is sent.
          items:
            type: string
          type: array
        isEnabled:
          description: Recurring scans state.
          type: boolean
      type: object
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow
      flows:
        implicit:
          authorizationUrl: 'https://login.microsoftonline.com/common/oauth2/authorize'
          scopes:
            user_impersonation: impersonate your user account
      type: oauth2

