openapi: 3.0.0
info:
  description: >-
    Get name and website-URL for airports by ICAO code. Covered airports are
    mostly in Germany.
  title: airportsapi
  version: v1
servers:
  - url: 'https://airport-web.appspot.com/_ah/api'
paths:
  '/airportsapi/v1/airports/{icao_code}':
    get:
      parameters:
        - in: path
          name: icao_code
          required: true
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiEndpointsAirportResponse'
          description: A successful response
      operationId: AirportApi_getAirport
components:
  schemas:
    ApiEndpointsAirportResponse:
      properties:
        ICAO:
          type: string
        last_update:
          type: string
        name:
          type: string
        url:
          type: string
      type: object
  securitySchemes:
    google_id_token:
      flows:
        implicit:
          authorizationUrl: /
          scopes: {}
      type: oauth2
      x-google-issuer: accounts.google.com
      x-google-jwks_uri: 'https://www.googleapis.com/oauth2/v1/certs'

