openapi: 3.0.0
x-badges: []
x-rapidapi-info:
  apiVersionId: apiversion_327f55e8-a89c-4f50-8f2c-425ca927c0c0
  apiId: api_1076b9b3-3ca0-4001-a63e-9b643b36b466
info:
  title: Tafqit
  description: Convert numbers to their Arabic text representation
  contact:
    name: Sami Morcos
    email: info@tafqit.com
    url: https://tafqit.com
  version: v1
  x-category: Education
  x-long-description: "Based on the notoriously difficult rules for numbers in Arabic,
    Tafqit API converts Arabic numerals into written Arabic text\nتحويل الأعداد العربية
    إلى ما يقابلها كتابة، مع مراعات التذكير والتأنيث. تحويل الارقام إلى حروف."
  x-website: tafqit.com
  x-public: true
  x-thumbnail: 
    https://rapidapi-prod-apis.s3.amazonaws.com/6d8ff169-b82c-4fc0-bebc-b0c8f2ee79d4.png
  x-version-lifecycle: current
servers:
- url: /
  description: Base URL
tags: []
paths:
  /convert:
    post:
      externalDocs:
        description: ''
        url: ''
      operationId: convert
      description: "Convert the number into its Arabic text representation\nحول العدد
        إلى ما يقابله كتابة"
      responses:
        '200':
          description: number converted to text successfully, تمت عملية التفقيط بنجاح
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                unit:
                  type: string
                  format: string
                  description: "The counted subject, be it a currency like درهم إماراتي\
                    \  or a size unit like متر مربع\nIf the unit does not appear in
                    the text result, it may not be supported. Please contact us to
                    add it."
                  example: ' ريال سعودي'
                hundreds_form:
                  type: string
                  format: string
                  description: 'Some use مائة others use مئة , both works in Arabic.
                    If left empty the default is مائة '
                  example: مائة
                the_number:
                  type: string
                  format: string
                  description: Put the number here. Decimal is supported by most units.
                  example: '2519.50'
